// Code generated by goppy-cli for goppy.orm. DO NOT EDIT.
package database

import (
	"context"
	time "time"

	uuid "github.com/google/uuid"
	"go.osspkg.com/goppy/v2/orm"
)

type RepoModels struct {
	orm        orm.ORM
	rtag, wtag string
}

func NewRepoModels(orm orm.ORM) *RepoModels {
	return &RepoModels{
		orm:  orm,
		rtag: "slave",
		wtag: "master",
	}
}

func (v *RepoModels) TagSlave() orm.Stmt {
	return v.orm.Tag(v.rtag)
}

func (v *RepoModels) TagMaster() orm.Stmt {
	return v.orm.Tag(v.wtag)
}

const sqlSettingCreateSettings = `INSERT INTO "setting" ("key", "value", "updated_at") 
			VALUES ($1, $2, $3) 
`

func (v *RepoModels) CreateSettings(ctx context.Context, ms []*Settings, opts ...CreateOption) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlSettingCreateSettings)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(` RETURNING ("id") `)
	buf.WriteString(`;`)

	return v.orm.Tag(v.wtag).Tx(ctx, "setting_create", func(tx orm.Tx) {
		for _, m := range ms {
			tx.Query(func(q orm.Querier) {
				q.SQL(buf.String(), m.Key, m.Value, m.UpdatedAt)
				q.Bind(func(bind orm.Scanner) error {
					return bind.Scan(&m.ID)
				})
			})
		}
	})
}

const sqlSettingUpdateSettings = `UPDATE "setting" SET 
			"key" = $1, "value" = $2, "updated_at" = $3
			 WHERE "id" = $4;
`

func (v *RepoModels) UpdateSettings(ctx context.Context, ms []*Settings) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	if len(ms) > 1 {
		return v.orm.Tag(v.wtag).Tx(ctx, "setting_update", func(tx orm.Tx) {
			tx.Exec(func(e orm.Executor) {
				e.SQL(sqlSettingUpdateSettings)
				for _, m := range ms {
					e.Params(m.Key, m.Value, m.UpdatedAt, m.ID)
				}
			})
		})
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "setting_update", func(e orm.Executor) {
		e.SQL(sqlSettingUpdateSettings, ms[0].Key, ms[0].Value, ms[0].UpdatedAt, ms[0].ID)
	})
}

const sqlSettingDeleteSettings = `DELETE FROM "setting"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) DeleteSettings(ctx context.Context, pk []int64) error {
	if len(pk) == 0 {
		return nil
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "setting_delete", func(e orm.Executor) {
		e.SQL(sqlSettingDeleteSettings, pk)
	})
}

const sqlSettingReadSettingsAll = `SELECT "id", "key", "value", "updated_at"
			 FROM "setting";
`

func (v *RepoModels) ReadSettingsAll(ctx context.Context) ([]Settings,
	error) {
	result := make([]Settings, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "setting_read_all", func(q orm.Querier) {
		q.SQL(sqlSettingReadSettingsAll)
		q.Bind(func(bind orm.Scanner) error {
			m := Settings{}
			if e := bind.Scan(&m.ID, &m.Key, &m.Value, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlSettingReadSettingsByID = `SELECT "id", "key", "value", "updated_at"
			 FROM "setting"
			 WHERE "id" = ANY($1)
`

func (v *RepoModels) ReadSettingsByID(
	ctx context.Context, args []int64, opts ...ReadOption,
) ([]Settings, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlSettingReadSettingsByID)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]Settings, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "setting_read_by_id", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := Settings{}
			if e := bind.Scan(&m.ID, &m.Key, &m.Value, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlSettingReadSettingsByKey = `SELECT "id", "key", "value", "updated_at"
			 FROM "setting"
			 WHERE "key" = ANY($1)
`

func (v *RepoModels) ReadSettingsByKey(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]Settings, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlSettingReadSettingsByKey)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]Settings, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "setting_read_by_key", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := Settings{}
			if e := bind.Scan(&m.ID, &m.Key, &m.Value, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlSettingCountSettingsByID = `SELECT COUNT(*) 
			 FROM "setting"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) CountSettingsByID(
	ctx context.Context, args []int64,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "setting_count_by_id", func(q orm.Querier) {
		q.SQL(sqlSettingCountSettingsByID, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlSettingCountSettingsByKey = `SELECT COUNT(*) 
			 FROM "setting"
			 WHERE "key" = ANY($1);
`

func (v *RepoModels) CountSettingsByKey(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "setting_count_by_key", func(q orm.Querier) {
		q.SQL(sqlSettingCountSettingsByKey, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlApiTokenCreateApiToken = `INSERT INTO "api_token" ("token", "qtype", "domain", "disabled", "updated_at") 
			VALUES ($1, $2, $3, $4, $5) 
`

func (v *RepoModels) CreateApiToken(ctx context.Context, ms []*ApiToken, opts ...CreateOption) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlApiTokenCreateApiToken)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(` RETURNING ("id") `)
	buf.WriteString(`;`)

	return v.orm.Tag(v.wtag).Tx(ctx, "api_token_create", func(tx orm.Tx) {
		for _, m := range ms {
			tx.Query(func(q orm.Querier) {
				q.SQL(buf.String(), m.Token, m.QType, m.Domain, m.Disabled, m.UpdatedAt)
				q.Bind(func(bind orm.Scanner) error {
					return bind.Scan(&m.ID)
				})
			})
		}
	})
}

const sqlApiTokenUpdateApiToken = `UPDATE "api_token" SET 
			"token" = $1, "qtype" = $2, "domain" = $3, "disabled" = $4, "updated_at" = $5
			 WHERE "id" = $6;
`

func (v *RepoModels) UpdateApiToken(ctx context.Context, ms []*ApiToken) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	if len(ms) > 1 {
		return v.orm.Tag(v.wtag).Tx(ctx, "api_token_update", func(tx orm.Tx) {
			tx.Exec(func(e orm.Executor) {
				e.SQL(sqlApiTokenUpdateApiToken)
				for _, m := range ms {
					e.Params(m.Token, m.QType, m.Domain, m.Disabled, m.UpdatedAt, m.ID)
				}
			})
		})
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "api_token_update", func(e orm.Executor) {
		e.SQL(sqlApiTokenUpdateApiToken, ms[0].Token, ms[0].QType, ms[0].Domain, ms[0].Disabled, ms[0].UpdatedAt, ms[0].ID)
	})
}

const sqlApiTokenDeleteApiToken = `DELETE FROM "api_token"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) DeleteApiToken(ctx context.Context, pk []int64) error {
	if len(pk) == 0 {
		return nil
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "api_token_delete", func(e orm.Executor) {
		e.SQL(sqlApiTokenDeleteApiToken, pk)
	})
}

const sqlApiTokenReadApiTokenAll = `SELECT "id", "token", "qtype", "domain", "disabled", "updated_at"
			 FROM "api_token";
`

func (v *RepoModels) ReadApiTokenAll(ctx context.Context) ([]ApiToken,
	error) {
	result := make([]ApiToken, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_read_all", func(q orm.Querier) {
		q.SQL(sqlApiTokenReadApiTokenAll)
		q.Bind(func(bind orm.Scanner) error {
			m := ApiToken{}
			if e := bind.Scan(&m.ID, &m.Token, &m.QType, &m.Domain, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlApiTokenReadApiTokenByID = `SELECT "id", "token", "qtype", "domain", "disabled", "updated_at"
			 FROM "api_token"
			 WHERE "id" = ANY($1)
`

func (v *RepoModels) ReadApiTokenByID(
	ctx context.Context, args []int64, opts ...ReadOption,
) ([]ApiToken, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlApiTokenReadApiTokenByID)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]ApiToken, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_read_by_id", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := ApiToken{}
			if e := bind.Scan(&m.ID, &m.Token, &m.QType, &m.Domain, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlApiTokenReadApiTokenByToken = `SELECT "id", "token", "qtype", "domain", "disabled", "updated_at"
			 FROM "api_token"
			 WHERE "token" = ANY($1)
`

func (v *RepoModels) ReadApiTokenByToken(
	ctx context.Context, args []uuid.UUID, opts ...ReadOption,
) ([]ApiToken, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlApiTokenReadApiTokenByToken)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]ApiToken, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_read_by_token", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := ApiToken{}
			if e := bind.Scan(&m.ID, &m.Token, &m.QType, &m.Domain, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlApiTokenReadApiTokenByQType = `SELECT "id", "token", "qtype", "domain", "disabled", "updated_at"
			 FROM "api_token"
			 WHERE "qtype" = ANY($1)
`

func (v *RepoModels) ReadApiTokenByQType(
	ctx context.Context, args []uint16, opts ...ReadOption,
) ([]ApiToken, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlApiTokenReadApiTokenByQType)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]ApiToken, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_read_by_qtype", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := ApiToken{}
			if e := bind.Scan(&m.ID, &m.Token, &m.QType, &m.Domain, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlApiTokenReadApiTokenByDomain = `SELECT "id", "token", "qtype", "domain", "disabled", "updated_at"
			 FROM "api_token"
			 WHERE "domain" = ANY($1)
`

func (v *RepoModels) ReadApiTokenByDomain(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]ApiToken, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlApiTokenReadApiTokenByDomain)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]ApiToken, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_read_by_domain", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := ApiToken{}
			if e := bind.Scan(&m.ID, &m.Token, &m.QType, &m.Domain, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlApiTokenReadApiTokenByDisabled = `SELECT "id", "token", "qtype", "domain", "disabled", "updated_at"
			 FROM "api_token"
			 WHERE "disabled" = ANY($1)
`

func (v *RepoModels) ReadApiTokenByDisabled(
	ctx context.Context, args []bool, opts ...ReadOption,
) ([]ApiToken, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlApiTokenReadApiTokenByDisabled)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]ApiToken, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_read_by_disabled", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := ApiToken{}
			if e := bind.Scan(&m.ID, &m.Token, &m.QType, &m.Domain, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlApiTokenCountApiTokenByID = `SELECT COUNT(*) 
			 FROM "api_token"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) CountApiTokenByID(
	ctx context.Context, args []int64,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_count_by_id", func(q orm.Querier) {
		q.SQL(sqlApiTokenCountApiTokenByID, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlApiTokenCountApiTokenByToken = `SELECT COUNT(*) 
			 FROM "api_token"
			 WHERE "token" = ANY($1);
`

func (v *RepoModels) CountApiTokenByToken(
	ctx context.Context, args []uuid.UUID,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_count_by_token", func(q orm.Querier) {
		q.SQL(sqlApiTokenCountApiTokenByToken, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlApiTokenCountApiTokenByQType = `SELECT COUNT(*) 
			 FROM "api_token"
			 WHERE "qtype" = ANY($1);
`

func (v *RepoModels) CountApiTokenByQType(
	ctx context.Context, args []uint16,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_count_by_qtype", func(q orm.Querier) {
		q.SQL(sqlApiTokenCountApiTokenByQType, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlApiTokenCountApiTokenByDomain = `SELECT COUNT(*) 
			 FROM "api_token"
			 WHERE "domain" = ANY($1);
`

func (v *RepoModels) CountApiTokenByDomain(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_count_by_domain", func(q orm.Querier) {
		q.SQL(sqlApiTokenCountApiTokenByDomain, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlApiTokenCountApiTokenByDisabled = `SELECT COUNT(*) 
			 FROM "api_token"
			 WHERE "disabled" = ANY($1);
`

func (v *RepoModels) CountApiTokenByDisabled(
	ctx context.Context, args []bool,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "api_token_count_by_disabled", func(q orm.Querier) {
		q.SQL(sqlApiTokenCountApiTokenByDisabled, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlNameSpaceCreateNS = `INSERT INTO "name_space" ("zone", "value", "disabled", "updated_at") 
			VALUES ($1, $2, $3, $4) 
`

func (v *RepoModels) CreateNS(ctx context.Context, ms []*NS, opts ...CreateOption) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlNameSpaceCreateNS)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(` RETURNING ("id") `)
	buf.WriteString(`;`)

	return v.orm.Tag(v.wtag).Tx(ctx, "name_space_create", func(tx orm.Tx) {
		for _, m := range ms {
			tx.Query(func(q orm.Querier) {
				q.SQL(buf.String(), m.Zone, m.Value, m.Disabled, m.UpdatedAt)
				q.Bind(func(bind orm.Scanner) error {
					return bind.Scan(&m.ID)
				})
			})
		}
	})
}

const sqlNameSpaceUpdateNS = `UPDATE "name_space" SET 
			"zone" = $1, "value" = $2, "disabled" = $3, "updated_at" = $4
			 WHERE "id" = $5;
`

func (v *RepoModels) UpdateNS(ctx context.Context, ms []*NS) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	if len(ms) > 1 {
		return v.orm.Tag(v.wtag).Tx(ctx, "name_space_update", func(tx orm.Tx) {
			tx.Exec(func(e orm.Executor) {
				e.SQL(sqlNameSpaceUpdateNS)
				for _, m := range ms {
					e.Params(m.Zone, m.Value, m.Disabled, m.UpdatedAt, m.ID)
				}
			})
		})
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "name_space_update", func(e orm.Executor) {
		e.SQL(sqlNameSpaceUpdateNS, ms[0].Zone, ms[0].Value, ms[0].Disabled, ms[0].UpdatedAt, ms[0].ID)
	})
}

const sqlNameSpaceDeleteNS = `DELETE FROM "name_space"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) DeleteNS(ctx context.Context, pk []int64) error {
	if len(pk) == 0 {
		return nil
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "name_space_delete", func(e orm.Executor) {
		e.SQL(sqlNameSpaceDeleteNS, pk)
	})
}

const sqlNameSpaceReadNSAll = `SELECT "id", "zone", "value", "disabled", "updated_at"
			 FROM "name_space";
`

func (v *RepoModels) ReadNSAll(ctx context.Context) ([]NS,
	error) {
	result := make([]NS, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "name_space_read_all", func(q orm.Querier) {
		q.SQL(sqlNameSpaceReadNSAll)
		q.Bind(func(bind orm.Scanner) error {
			m := NS{}
			if e := bind.Scan(&m.ID, &m.Zone, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlNameSpaceReadNSByID = `SELECT "id", "zone", "value", "disabled", "updated_at"
			 FROM "name_space"
			 WHERE "id" = ANY($1)
`

func (v *RepoModels) ReadNSByID(
	ctx context.Context, args []int64, opts ...ReadOption,
) ([]NS, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlNameSpaceReadNSByID)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]NS, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "name_space_read_by_id", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := NS{}
			if e := bind.Scan(&m.ID, &m.Zone, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlNameSpaceReadNSByZone = `SELECT "id", "zone", "value", "disabled", "updated_at"
			 FROM "name_space"
			 WHERE "zone" = ANY($1)
`

func (v *RepoModels) ReadNSByZone(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]NS, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlNameSpaceReadNSByZone)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]NS, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "name_space_read_by_zone", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := NS{}
			if e := bind.Scan(&m.ID, &m.Zone, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlNameSpaceReadNSByValue = `SELECT "id", "zone", "value", "disabled", "updated_at"
			 FROM "name_space"
			 WHERE "value" = ANY($1)
`

func (v *RepoModels) ReadNSByValue(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]NS, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlNameSpaceReadNSByValue)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]NS, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "name_space_read_by_value", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := NS{}
			if e := bind.Scan(&m.ID, &m.Zone, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlNameSpaceReadNSByDisabled = `SELECT "id", "zone", "value", "disabled", "updated_at"
			 FROM "name_space"
			 WHERE "disabled" = ANY($1)
`

func (v *RepoModels) ReadNSByDisabled(
	ctx context.Context, args []bool, opts ...ReadOption,
) ([]NS, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlNameSpaceReadNSByDisabled)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]NS, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "name_space_read_by_disabled", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := NS{}
			if e := bind.Scan(&m.ID, &m.Zone, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlNameSpaceCountNSByID = `SELECT COUNT(*) 
			 FROM "name_space"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) CountNSByID(
	ctx context.Context, args []int64,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "name_space_count_by_id", func(q orm.Querier) {
		q.SQL(sqlNameSpaceCountNSByID, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlNameSpaceCountNSByZone = `SELECT COUNT(*) 
			 FROM "name_space"
			 WHERE "zone" = ANY($1);
`

func (v *RepoModels) CountNSByZone(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "name_space_count_by_zone", func(q orm.Querier) {
		q.SQL(sqlNameSpaceCountNSByZone, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlNameSpaceCountNSByValue = `SELECT COUNT(*) 
			 FROM "name_space"
			 WHERE "value" = ANY($1);
`

func (v *RepoModels) CountNSByValue(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "name_space_count_by_value", func(q orm.Querier) {
		q.SQL(sqlNameSpaceCountNSByValue, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlNameSpaceCountNSByDisabled = `SELECT COUNT(*) 
			 FROM "name_space"
			 WHERE "disabled" = ANY($1);
`

func (v *RepoModels) CountNSByDisabled(
	ctx context.Context, args []bool,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "name_space_count_by_disabled", func(q orm.Querier) {
		q.SQL(sqlNameSpaceCountNSByDisabled, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlDnsHistoryCreateHistory = `INSERT INTO "dns_history" ("domain", "qtype", "value", "disabled", "updated_at") 
			VALUES ($1, $2, $3, $4, $5) 
`

func (v *RepoModels) CreateHistory(ctx context.Context, ms []*History, opts ...CreateOption) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlDnsHistoryCreateHistory)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(` RETURNING ("id") `)
	buf.WriteString(`;`)

	return v.orm.Tag(v.wtag).Tx(ctx, "dns_history_create", func(tx orm.Tx) {
		for _, m := range ms {
			tx.Query(func(q orm.Querier) {
				q.SQL(buf.String(), m.Domain, m.QType, m.Value, m.Disabled, m.UpdatedAt)
				q.Bind(func(bind orm.Scanner) error {
					return bind.Scan(&m.ID)
				})
			})
		}
	})
}

const sqlDnsHistoryUpdateHistory = `UPDATE "dns_history" SET 
			"domain" = $1, "qtype" = $2, "value" = $3, "disabled" = $4, "updated_at" = $5
			 WHERE "id" = $6;
`

func (v *RepoModels) UpdateHistory(ctx context.Context, ms []*History) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	if len(ms) > 1 {
		return v.orm.Tag(v.wtag).Tx(ctx, "dns_history_update", func(tx orm.Tx) {
			tx.Exec(func(e orm.Executor) {
				e.SQL(sqlDnsHistoryUpdateHistory)
				for _, m := range ms {
					e.Params(m.Domain, m.QType, m.Value, m.Disabled, m.UpdatedAt, m.ID)
				}
			})
		})
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "dns_history_update", func(e orm.Executor) {
		e.SQL(sqlDnsHistoryUpdateHistory, ms[0].Domain, ms[0].QType, ms[0].Value, ms[0].Disabled, ms[0].UpdatedAt, ms[0].ID)
	})
}

const sqlDnsHistoryDeleteHistory = `DELETE FROM "dns_history"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) DeleteHistory(ctx context.Context, pk []int64) error {
	if len(pk) == 0 {
		return nil
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "dns_history_delete", func(e orm.Executor) {
		e.SQL(sqlDnsHistoryDeleteHistory, pk)
	})
}

const sqlDnsHistoryReadHistoryAll = `SELECT "id", "domain", "qtype", "value", "disabled", "updated_at"
			 FROM "dns_history";
`

func (v *RepoModels) ReadHistoryAll(ctx context.Context) ([]History,
	error) {
	result := make([]History, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_read_all", func(q orm.Querier) {
		q.SQL(sqlDnsHistoryReadHistoryAll)
		q.Bind(func(bind orm.Scanner) error {
			m := History{}
			if e := bind.Scan(&m.ID, &m.Domain, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlDnsHistoryReadHistoryByID = `SELECT "id", "domain", "qtype", "value", "disabled", "updated_at"
			 FROM "dns_history"
			 WHERE "id" = ANY($1)
`

func (v *RepoModels) ReadHistoryByID(
	ctx context.Context, args []int64, opts ...ReadOption,
) ([]History, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlDnsHistoryReadHistoryByID)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]History, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_read_by_id", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := History{}
			if e := bind.Scan(&m.ID, &m.Domain, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlDnsHistoryReadHistoryByDomain = `SELECT "id", "domain", "qtype", "value", "disabled", "updated_at"
			 FROM "dns_history"
			 WHERE "domain" = ANY($1)
`

func (v *RepoModels) ReadHistoryByDomain(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]History, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlDnsHistoryReadHistoryByDomain)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]History, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_read_by_domain", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := History{}
			if e := bind.Scan(&m.ID, &m.Domain, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlDnsHistoryReadHistoryByQType = `SELECT "id", "domain", "qtype", "value", "disabled", "updated_at"
			 FROM "dns_history"
			 WHERE "qtype" = ANY($1)
`

func (v *RepoModels) ReadHistoryByQType(
	ctx context.Context, args []uint16, opts ...ReadOption,
) ([]History, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlDnsHistoryReadHistoryByQType)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]History, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_read_by_qtype", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := History{}
			if e := bind.Scan(&m.ID, &m.Domain, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlDnsHistoryReadHistoryByValue = `SELECT "id", "domain", "qtype", "value", "disabled", "updated_at"
			 FROM "dns_history"
			 WHERE "value" = ANY($1)
`

func (v *RepoModels) ReadHistoryByValue(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]History, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlDnsHistoryReadHistoryByValue)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]History, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_read_by_value", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := History{}
			if e := bind.Scan(&m.ID, &m.Domain, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlDnsHistoryReadHistoryByDisabled = `SELECT "id", "domain", "qtype", "value", "disabled", "updated_at"
			 FROM "dns_history"
			 WHERE "disabled" = ANY($1)
`

func (v *RepoModels) ReadHistoryByDisabled(
	ctx context.Context, args []bool, opts ...ReadOption,
) ([]History, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlDnsHistoryReadHistoryByDisabled)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]History, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_read_by_disabled", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := History{}
			if e := bind.Scan(&m.ID, &m.Domain, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlDnsHistoryCountHistoryByID = `SELECT COUNT(*) 
			 FROM "dns_history"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) CountHistoryByID(
	ctx context.Context, args []int64,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_count_by_id", func(q orm.Querier) {
		q.SQL(sqlDnsHistoryCountHistoryByID, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlDnsHistoryCountHistoryByDomain = `SELECT COUNT(*) 
			 FROM "dns_history"
			 WHERE "domain" = ANY($1);
`

func (v *RepoModels) CountHistoryByDomain(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_count_by_domain", func(q orm.Querier) {
		q.SQL(sqlDnsHistoryCountHistoryByDomain, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlDnsHistoryCountHistoryByQType = `SELECT COUNT(*) 
			 FROM "dns_history"
			 WHERE "qtype" = ANY($1);
`

func (v *RepoModels) CountHistoryByQType(
	ctx context.Context, args []uint16,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_count_by_qtype", func(q orm.Querier) {
		q.SQL(sqlDnsHistoryCountHistoryByQType, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlDnsHistoryCountHistoryByValue = `SELECT COUNT(*) 
			 FROM "dns_history"
			 WHERE "value" = ANY($1);
`

func (v *RepoModels) CountHistoryByValue(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_count_by_value", func(q orm.Querier) {
		q.SQL(sqlDnsHistoryCountHistoryByValue, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlDnsHistoryCountHistoryByDisabled = `SELECT COUNT(*) 
			 FROM "dns_history"
			 WHERE "disabled" = ANY($1);
`

func (v *RepoModels) CountHistoryByDisabled(
	ctx context.Context, args []bool,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "dns_history_count_by_disabled", func(q orm.Querier) {
		q.SQL(sqlDnsHistoryCountHistoryByDisabled, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlAdblockLinkCreateAdblockLink = `INSERT INTO "adblock_link" ("link", "disabled", "updated_at") 
			VALUES ($1, $2, $3) 
`

func (v *RepoModels) CreateAdblockLink(ctx context.Context, ms []*AdblockLink, opts ...CreateOption) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockLinkCreateAdblockLink)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(` RETURNING ("id") `)
	buf.WriteString(`;`)

	return v.orm.Tag(v.wtag).Tx(ctx, "adblock_link_create", func(tx orm.Tx) {
		for _, m := range ms {
			tx.Query(func(q orm.Querier) {
				q.SQL(buf.String(), m.Link, m.Disabled, m.UpdatedAt)
				q.Bind(func(bind orm.Scanner) error {
					return bind.Scan(&m.ID)
				})
			})
		}
	})
}

const sqlAdblockLinkUpdateAdblockLink = `UPDATE "adblock_link" SET 
			"link" = $1, "disabled" = $2, "updated_at" = $3
			 WHERE "id" = $4;
`

func (v *RepoModels) UpdateAdblockLink(ctx context.Context, ms []*AdblockLink) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	if len(ms) > 1 {
		return v.orm.Tag(v.wtag).Tx(ctx, "adblock_link_update", func(tx orm.Tx) {
			tx.Exec(func(e orm.Executor) {
				e.SQL(sqlAdblockLinkUpdateAdblockLink)
				for _, m := range ms {
					e.Params(m.Link, m.Disabled, m.UpdatedAt, m.ID)
				}
			})
		})
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "adblock_link_update", func(e orm.Executor) {
		e.SQL(sqlAdblockLinkUpdateAdblockLink, ms[0].Link, ms[0].Disabled, ms[0].UpdatedAt, ms[0].ID)
	})
}

const sqlAdblockLinkDeleteAdblockLink = `DELETE FROM "adblock_link"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) DeleteAdblockLink(ctx context.Context, pk []int64) error {
	if len(pk) == 0 {
		return nil
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "adblock_link_delete", func(e orm.Executor) {
		e.SQL(sqlAdblockLinkDeleteAdblockLink, pk)
	})
}

const sqlAdblockLinkReadAdblockLinkAll = `SELECT "id", "link", "disabled", "updated_at"
			 FROM "adblock_link";
`

func (v *RepoModels) ReadAdblockLinkAll(ctx context.Context) ([]AdblockLink,
	error) {
	result := make([]AdblockLink, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_link_read_all", func(q orm.Querier) {
		q.SQL(sqlAdblockLinkReadAdblockLinkAll)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockLink{}
			if e := bind.Scan(&m.ID, &m.Link, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockLinkReadAdblockLinkByID = `SELECT "id", "link", "disabled", "updated_at"
			 FROM "adblock_link"
			 WHERE "id" = ANY($1)
`

func (v *RepoModels) ReadAdblockLinkByID(
	ctx context.Context, args []int64, opts ...ReadOption,
) ([]AdblockLink, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockLinkReadAdblockLinkByID)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]AdblockLink, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_link_read_by_id", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockLink{}
			if e := bind.Scan(&m.ID, &m.Link, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockLinkReadAdblockLinkByLink = `SELECT "id", "link", "disabled", "updated_at"
			 FROM "adblock_link"
			 WHERE "link" = ANY($1)
`

func (v *RepoModels) ReadAdblockLinkByLink(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]AdblockLink, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockLinkReadAdblockLinkByLink)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]AdblockLink, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_link_read_by_link", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockLink{}
			if e := bind.Scan(&m.ID, &m.Link, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockLinkReadAdblockLinkByDisabled = `SELECT "id", "link", "disabled", "updated_at"
			 FROM "adblock_link"
			 WHERE "disabled" = ANY($1)
`

func (v *RepoModels) ReadAdblockLinkByDisabled(
	ctx context.Context, args []bool, opts ...ReadOption,
) ([]AdblockLink, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockLinkReadAdblockLinkByDisabled)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]AdblockLink, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_link_read_by_disabled", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockLink{}
			if e := bind.Scan(&m.ID, &m.Link, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockLinkCountAdblockLinkByID = `SELECT COUNT(*) 
			 FROM "adblock_link"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) CountAdblockLinkByID(
	ctx context.Context, args []int64,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_link_count_by_id", func(q orm.Querier) {
		q.SQL(sqlAdblockLinkCountAdblockLinkByID, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlAdblockLinkCountAdblockLinkByLink = `SELECT COUNT(*) 
			 FROM "adblock_link"
			 WHERE "link" = ANY($1);
`

func (v *RepoModels) CountAdblockLinkByLink(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_link_count_by_link", func(q orm.Querier) {
		q.SQL(sqlAdblockLinkCountAdblockLinkByLink, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlAdblockLinkCountAdblockLinkByDisabled = `SELECT COUNT(*) 
			 FROM "adblock_link"
			 WHERE "disabled" = ANY($1);
`

func (v *RepoModels) CountAdblockLinkByDisabled(
	ctx context.Context, args []bool,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_link_count_by_disabled", func(q orm.Querier) {
		q.SQL(sqlAdblockLinkCountAdblockLinkByDisabled, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlAdblockRuleCreateAdblockRule = `INSERT INTO "adblock_rule" ("link_id", "zone", "rule", "disabled", "updated_at") 
			VALUES ($1, $2, $3, $4, $5) 
`

func (v *RepoModels) CreateAdblockRule(ctx context.Context, ms []*AdblockRule, opts ...CreateOption) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockRuleCreateAdblockRule)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(` RETURNING ("id") `)
	buf.WriteString(`;`)

	return v.orm.Tag(v.wtag).Tx(ctx, "adblock_rule_create", func(tx orm.Tx) {
		for _, m := range ms {
			tx.Query(func(q orm.Querier) {
				q.SQL(buf.String(), m.LinkId, m.Zone, m.Rule, m.Disabled, m.UpdatedAt)
				q.Bind(func(bind orm.Scanner) error {
					return bind.Scan(&m.ID)
				})
			})
		}
	})
}

const sqlAdblockRuleUpdateAdblockRule = `UPDATE "adblock_rule" SET 
			"link_id" = $1, "zone" = $2, "rule" = $3, "disabled" = $4, "updated_at" = $5
			 WHERE "id" = $6;
`

func (v *RepoModels) UpdateAdblockRule(ctx context.Context, ms []*AdblockRule) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	if len(ms) > 1 {
		return v.orm.Tag(v.wtag).Tx(ctx, "adblock_rule_update", func(tx orm.Tx) {
			tx.Exec(func(e orm.Executor) {
				e.SQL(sqlAdblockRuleUpdateAdblockRule)
				for _, m := range ms {
					e.Params(m.LinkId, m.Zone, m.Rule, m.Disabled, m.UpdatedAt, m.ID)
				}
			})
		})
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "adblock_rule_update", func(e orm.Executor) {
		e.SQL(sqlAdblockRuleUpdateAdblockRule, ms[0].LinkId, ms[0].Zone, ms[0].Rule, ms[0].Disabled, ms[0].UpdatedAt, ms[0].ID)
	})
}

const sqlAdblockRuleDeleteAdblockRule = `DELETE FROM "adblock_rule"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) DeleteAdblockRule(ctx context.Context, pk []int64) error {
	if len(pk) == 0 {
		return nil
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "adblock_rule_delete", func(e orm.Executor) {
		e.SQL(sqlAdblockRuleDeleteAdblockRule, pk)
	})
}

const sqlAdblockRuleReadAdblockRuleAll = `SELECT "id", "link_id", "zone", "rule", "disabled", "updated_at"
			 FROM "adblock_rule";
`

func (v *RepoModels) ReadAdblockRuleAll(ctx context.Context) ([]AdblockRule,
	error) {
	result := make([]AdblockRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_read_all", func(q orm.Querier) {
		q.SQL(sqlAdblockRuleReadAdblockRuleAll)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockRule{}
			if e := bind.Scan(&m.ID, &m.LinkId, &m.Zone, &m.Rule, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockRuleReadAdblockRuleByID = `SELECT "id", "link_id", "zone", "rule", "disabled", "updated_at"
			 FROM "adblock_rule"
			 WHERE "id" = ANY($1)
`

func (v *RepoModels) ReadAdblockRuleByID(
	ctx context.Context, args []int64, opts ...ReadOption,
) ([]AdblockRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockRuleReadAdblockRuleByID)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]AdblockRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_read_by_id", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockRule{}
			if e := bind.Scan(&m.ID, &m.LinkId, &m.Zone, &m.Rule, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockRuleReadAdblockRuleByLinkId = `SELECT "id", "link_id", "zone", "rule", "disabled", "updated_at"
			 FROM "adblock_rule"
			 WHERE "link_id" = ANY($1)
`

func (v *RepoModels) ReadAdblockRuleByLinkId(
	ctx context.Context, args []int64, opts ...ReadOption,
) ([]AdblockRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockRuleReadAdblockRuleByLinkId)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]AdblockRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_read_by_link_id", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockRule{}
			if e := bind.Scan(&m.ID, &m.LinkId, &m.Zone, &m.Rule, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockRuleReadAdblockRuleByZone = `SELECT "id", "link_id", "zone", "rule", "disabled", "updated_at"
			 FROM "adblock_rule"
			 WHERE "zone" = ANY($1)
`

func (v *RepoModels) ReadAdblockRuleByZone(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]AdblockRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockRuleReadAdblockRuleByZone)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]AdblockRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_read_by_zone", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockRule{}
			if e := bind.Scan(&m.ID, &m.LinkId, &m.Zone, &m.Rule, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockRuleReadAdblockRuleByRule = `SELECT "id", "link_id", "zone", "rule", "disabled", "updated_at"
			 FROM "adblock_rule"
			 WHERE "rule" = ANY($1)
`

func (v *RepoModels) ReadAdblockRuleByRule(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]AdblockRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockRuleReadAdblockRuleByRule)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]AdblockRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_read_by_rule", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockRule{}
			if e := bind.Scan(&m.ID, &m.LinkId, &m.Zone, &m.Rule, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockRuleReadAdblockRuleByDisabled = `SELECT "id", "link_id", "zone", "rule", "disabled", "updated_at"
			 FROM "adblock_rule"
			 WHERE "disabled" = ANY($1)
`

func (v *RepoModels) ReadAdblockRuleByDisabled(
	ctx context.Context, args []bool, opts ...ReadOption,
) ([]AdblockRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlAdblockRuleReadAdblockRuleByDisabled)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]AdblockRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_read_by_disabled", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := AdblockRule{}
			if e := bind.Scan(&m.ID, &m.LinkId, &m.Zone, &m.Rule, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlAdblockRuleCountAdblockRuleByID = `SELECT COUNT(*) 
			 FROM "adblock_rule"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) CountAdblockRuleByID(
	ctx context.Context, args []int64,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_count_by_id", func(q orm.Querier) {
		q.SQL(sqlAdblockRuleCountAdblockRuleByID, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlAdblockRuleCountAdblockRuleByLinkId = `SELECT COUNT(*) 
			 FROM "adblock_rule"
			 WHERE "link_id" = ANY($1);
`

func (v *RepoModels) CountAdblockRuleByLinkId(
	ctx context.Context, args []int64,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_count_by_link_id", func(q orm.Querier) {
		q.SQL(sqlAdblockRuleCountAdblockRuleByLinkId, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlAdblockRuleCountAdblockRuleByZone = `SELECT COUNT(*) 
			 FROM "adblock_rule"
			 WHERE "zone" = ANY($1);
`

func (v *RepoModels) CountAdblockRuleByZone(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_count_by_zone", func(q orm.Querier) {
		q.SQL(sqlAdblockRuleCountAdblockRuleByZone, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlAdblockRuleCountAdblockRuleByRule = `SELECT COUNT(*) 
			 FROM "adblock_rule"
			 WHERE "rule" = ANY($1);
`

func (v *RepoModels) CountAdblockRuleByRule(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_count_by_rule", func(q orm.Querier) {
		q.SQL(sqlAdblockRuleCountAdblockRuleByRule, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlAdblockRuleCountAdblockRuleByDisabled = `SELECT COUNT(*) 
			 FROM "adblock_rule"
			 WHERE "disabled" = ANY($1);
`

func (v *RepoModels) CountAdblockRuleByDisabled(
	ctx context.Context, args []bool,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "adblock_rule_count_by_disabled", func(q orm.Querier) {
		q.SQL(sqlAdblockRuleCountAdblockRuleByDisabled, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlRegexpRuleCreateRegexpRule = `INSERT INTO "regexp_rule" ("rule", "qtype", "value", "disabled", "updated_at") 
			VALUES ($1, $2, $3, $4, $5) 
`

func (v *RepoModels) CreateRegexpRule(ctx context.Context, ms []*RegexpRule, opts ...CreateOption) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlRegexpRuleCreateRegexpRule)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(` RETURNING ("id") `)
	buf.WriteString(`;`)

	return v.orm.Tag(v.wtag).Tx(ctx, "regexp_rule_create", func(tx orm.Tx) {
		for _, m := range ms {
			tx.Query(func(q orm.Querier) {
				q.SQL(buf.String(), m.Rule, m.QType, m.Value, m.Disabled, m.UpdatedAt)
				q.Bind(func(bind orm.Scanner) error {
					return bind.Scan(&m.ID)
				})
			})
		}
	})
}

const sqlRegexpRuleUpdateRegexpRule = `UPDATE "regexp_rule" SET 
			"rule" = $1, "qtype" = $2, "value" = $3, "disabled" = $4, "updated_at" = $5
			 WHERE "id" = $6;
`

func (v *RepoModels) UpdateRegexpRule(ctx context.Context, ms []*RegexpRule) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	if len(ms) > 1 {
		return v.orm.Tag(v.wtag).Tx(ctx, "regexp_rule_update", func(tx orm.Tx) {
			tx.Exec(func(e orm.Executor) {
				e.SQL(sqlRegexpRuleUpdateRegexpRule)
				for _, m := range ms {
					e.Params(m.Rule, m.QType, m.Value, m.Disabled, m.UpdatedAt, m.ID)
				}
			})
		})
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "regexp_rule_update", func(e orm.Executor) {
		e.SQL(sqlRegexpRuleUpdateRegexpRule, ms[0].Rule, ms[0].QType, ms[0].Value, ms[0].Disabled, ms[0].UpdatedAt, ms[0].ID)
	})
}

const sqlRegexpRuleDeleteRegexpRule = `DELETE FROM "regexp_rule"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) DeleteRegexpRule(ctx context.Context, pk []int64) error {
	if len(pk) == 0 {
		return nil
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "regexp_rule_delete", func(e orm.Executor) {
		e.SQL(sqlRegexpRuleDeleteRegexpRule, pk)
	})
}

const sqlRegexpRuleReadRegexpRuleAll = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "regexp_rule";
`

func (v *RepoModels) ReadRegexpRuleAll(ctx context.Context) ([]RegexpRule,
	error) {
	result := make([]RegexpRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_read_all", func(q orm.Querier) {
		q.SQL(sqlRegexpRuleReadRegexpRuleAll)
		q.Bind(func(bind orm.Scanner) error {
			m := RegexpRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlRegexpRuleReadRegexpRuleByID = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "regexp_rule"
			 WHERE "id" = ANY($1)
`

func (v *RepoModels) ReadRegexpRuleByID(
	ctx context.Context, args []int64, opts ...ReadOption,
) ([]RegexpRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlRegexpRuleReadRegexpRuleByID)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]RegexpRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_read_by_id", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := RegexpRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlRegexpRuleReadRegexpRuleByRule = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "regexp_rule"
			 WHERE "rule" = ANY($1)
`

func (v *RepoModels) ReadRegexpRuleByRule(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]RegexpRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlRegexpRuleReadRegexpRuleByRule)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]RegexpRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_read_by_rule", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := RegexpRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlRegexpRuleReadRegexpRuleByQType = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "regexp_rule"
			 WHERE "qtype" = ANY($1)
`

func (v *RepoModels) ReadRegexpRuleByQType(
	ctx context.Context, args []uint16, opts ...ReadOption,
) ([]RegexpRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlRegexpRuleReadRegexpRuleByQType)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]RegexpRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_read_by_qtype", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := RegexpRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlRegexpRuleReadRegexpRuleByValue = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "regexp_rule"
			 WHERE "value" = ANY($1)
`

func (v *RepoModels) ReadRegexpRuleByValue(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]RegexpRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlRegexpRuleReadRegexpRuleByValue)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]RegexpRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_read_by_value", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := RegexpRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlRegexpRuleReadRegexpRuleByDisabled = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "regexp_rule"
			 WHERE "disabled" = ANY($1)
`

func (v *RepoModels) ReadRegexpRuleByDisabled(
	ctx context.Context, args []bool, opts ...ReadOption,
) ([]RegexpRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlRegexpRuleReadRegexpRuleByDisabled)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]RegexpRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_read_by_disabled", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := RegexpRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlRegexpRuleCountRegexpRuleByID = `SELECT COUNT(*) 
			 FROM "regexp_rule"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) CountRegexpRuleByID(
	ctx context.Context, args []int64,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_count_by_id", func(q orm.Querier) {
		q.SQL(sqlRegexpRuleCountRegexpRuleByID, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlRegexpRuleCountRegexpRuleByRule = `SELECT COUNT(*) 
			 FROM "regexp_rule"
			 WHERE "rule" = ANY($1);
`

func (v *RepoModels) CountRegexpRuleByRule(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_count_by_rule", func(q orm.Querier) {
		q.SQL(sqlRegexpRuleCountRegexpRuleByRule, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlRegexpRuleCountRegexpRuleByQType = `SELECT COUNT(*) 
			 FROM "regexp_rule"
			 WHERE "qtype" = ANY($1);
`

func (v *RepoModels) CountRegexpRuleByQType(
	ctx context.Context, args []uint16,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_count_by_qtype", func(q orm.Querier) {
		q.SQL(sqlRegexpRuleCountRegexpRuleByQType, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlRegexpRuleCountRegexpRuleByValue = `SELECT COUNT(*) 
			 FROM "regexp_rule"
			 WHERE "value" = ANY($1);
`

func (v *RepoModels) CountRegexpRuleByValue(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_count_by_value", func(q orm.Querier) {
		q.SQL(sqlRegexpRuleCountRegexpRuleByValue, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlRegexpRuleCountRegexpRuleByDisabled = `SELECT COUNT(*) 
			 FROM "regexp_rule"
			 WHERE "disabled" = ANY($1);
`

func (v *RepoModels) CountRegexpRuleByDisabled(
	ctx context.Context, args []bool,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "regexp_rule_count_by_disabled", func(q orm.Querier) {
		q.SQL(sqlRegexpRuleCountRegexpRuleByDisabled, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlStaticRuleCreateStaticRule = `INSERT INTO "static_rule" ("rule", "qtype", "value", "disabled", "updated_at") 
			VALUES ($1, $2, $3, $4, $5) 
`

func (v *RepoModels) CreateStaticRule(ctx context.Context, ms []*StaticRule, opts ...CreateOption) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlStaticRuleCreateStaticRule)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(` RETURNING ("id") `)
	buf.WriteString(`;`)

	return v.orm.Tag(v.wtag).Tx(ctx, "static_rule_create", func(tx orm.Tx) {
		for _, m := range ms {
			tx.Query(func(q orm.Querier) {
				q.SQL(buf.String(), m.Rule, m.QType, m.Value, m.Disabled, m.UpdatedAt)
				q.Bind(func(bind orm.Scanner) error {
					return bind.Scan(&m.ID)
				})
			})
		}
	})
}

const sqlStaticRuleUpdateStaticRule = `UPDATE "static_rule" SET 
			"rule" = $1, "qtype" = $2, "value" = $3, "disabled" = $4, "updated_at" = $5
			 WHERE "id" = $6;
`

func (v *RepoModels) UpdateStaticRule(ctx context.Context, ms []*StaticRule) error {
	if len(ms) == 0 {
		return nil
	}

	for _, m := range ms {
		m.UpdatedAt = time.Now()
	}

	if len(ms) > 1 {
		return v.orm.Tag(v.wtag).Tx(ctx, "static_rule_update", func(tx orm.Tx) {
			tx.Exec(func(e orm.Executor) {
				e.SQL(sqlStaticRuleUpdateStaticRule)
				for _, m := range ms {
					e.Params(m.Rule, m.QType, m.Value, m.Disabled, m.UpdatedAt, m.ID)
				}
			})
		})
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "static_rule_update", func(e orm.Executor) {
		e.SQL(sqlStaticRuleUpdateStaticRule, ms[0].Rule, ms[0].QType, ms[0].Value, ms[0].Disabled, ms[0].UpdatedAt, ms[0].ID)
	})
}

const sqlStaticRuleDeleteStaticRule = `DELETE FROM "static_rule"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) DeleteStaticRule(ctx context.Context, pk []int64) error {
	if len(pk) == 0 {
		return nil
	}

	return v.orm.Tag(v.wtag).Exec(ctx, "static_rule_delete", func(e orm.Executor) {
		e.SQL(sqlStaticRuleDeleteStaticRule, pk)
	})
}

const sqlStaticRuleReadStaticRuleAll = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "static_rule";
`

func (v *RepoModels) ReadStaticRuleAll(ctx context.Context) ([]StaticRule,
	error) {
	result := make([]StaticRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_read_all", func(q orm.Querier) {
		q.SQL(sqlStaticRuleReadStaticRuleAll)
		q.Bind(func(bind orm.Scanner) error {
			m := StaticRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlStaticRuleReadStaticRuleByID = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "static_rule"
			 WHERE "id" = ANY($1)
`

func (v *RepoModels) ReadStaticRuleByID(
	ctx context.Context, args []int64, opts ...ReadOption,
) ([]StaticRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlStaticRuleReadStaticRuleByID)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]StaticRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_read_by_id", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := StaticRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlStaticRuleReadStaticRuleByRule = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "static_rule"
			 WHERE "rule" = ANY($1)
`

func (v *RepoModels) ReadStaticRuleByRule(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]StaticRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlStaticRuleReadStaticRuleByRule)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]StaticRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_read_by_rule", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := StaticRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlStaticRuleReadStaticRuleByQType = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "static_rule"
			 WHERE "qtype" = ANY($1)
`

func (v *RepoModels) ReadStaticRuleByQType(
	ctx context.Context, args []uint16, opts ...ReadOption,
) ([]StaticRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlStaticRuleReadStaticRuleByQType)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]StaticRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_read_by_qtype", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := StaticRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlStaticRuleReadStaticRuleByValue = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "static_rule"
			 WHERE "value" = ANY($1)
`

func (v *RepoModels) ReadStaticRuleByValue(
	ctx context.Context, args []string, opts ...ReadOption,
) ([]StaticRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlStaticRuleReadStaticRuleByValue)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]StaticRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_read_by_value", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := StaticRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlStaticRuleReadStaticRuleByDisabled = `SELECT "id", "rule", "qtype", "value", "disabled", "updated_at"
			 FROM "static_rule"
			 WHERE "disabled" = ANY($1)
`

func (v *RepoModels) ReadStaticRuleByDisabled(
	ctx context.Context, args []bool, opts ...ReadOption,
) ([]StaticRule, error) {
	if len(args) == 0 {
		return nil, nil
	}

	buf := _sqlBuilderPool.Get()
	defer func() { _sqlBuilderPool.Put(buf) }()

	buf.WriteString(sqlStaticRuleReadStaticRuleByDisabled)
	for _, o := range opts {
		o(buf)
	}

	buf.WriteString(`;`)

	result := make([]StaticRule, 0, 2)
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_read_by_disabled", func(q orm.Querier) {
		q.SQL(buf.String(), args)
		q.Bind(func(bind orm.Scanner) error {
			m := StaticRule{}
			if e := bind.Scan(&m.ID, &m.Rule, &m.QType, &m.Value, &m.Disabled, &m.UpdatedAt); e != nil {
				return e
			}
			result = append(result, m)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

const sqlStaticRuleCountStaticRuleByID = `SELECT COUNT(*) 
			 FROM "static_rule"
			 WHERE "id" = ANY($1);
`

func (v *RepoModels) CountStaticRuleByID(
	ctx context.Context, args []int64,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_count_by_id", func(q orm.Querier) {
		q.SQL(sqlStaticRuleCountStaticRuleByID, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlStaticRuleCountStaticRuleByRule = `SELECT COUNT(*) 
			 FROM "static_rule"
			 WHERE "rule" = ANY($1);
`

func (v *RepoModels) CountStaticRuleByRule(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_count_by_rule", func(q orm.Querier) {
		q.SQL(sqlStaticRuleCountStaticRuleByRule, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlStaticRuleCountStaticRuleByQType = `SELECT COUNT(*) 
			 FROM "static_rule"
			 WHERE "qtype" = ANY($1);
`

func (v *RepoModels) CountStaticRuleByQType(
	ctx context.Context, args []uint16,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_count_by_qtype", func(q orm.Querier) {
		q.SQL(sqlStaticRuleCountStaticRuleByQType, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlStaticRuleCountStaticRuleByValue = `SELECT COUNT(*) 
			 FROM "static_rule"
			 WHERE "value" = ANY($1);
`

func (v *RepoModels) CountStaticRuleByValue(
	ctx context.Context, args []string,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_count_by_value", func(q orm.Querier) {
		q.SQL(sqlStaticRuleCountStaticRuleByValue, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}

const sqlStaticRuleCountStaticRuleByDisabled = `SELECT COUNT(*) 
			 FROM "static_rule"
			 WHERE "disabled" = ANY($1);
`

func (v *RepoModels) CountStaticRuleByDisabled(
	ctx context.Context, args []bool,
) (int64, error) {
	if len(args) == 0 {
		return 0, nil
	}

	var count int64
	err := v.orm.Tag(v.rtag).Query(ctx, "static_rule_count_by_disabled", func(q orm.Querier) {
		q.SQL(sqlStaticRuleCountStaticRuleByDisabled, args)
		q.Bind(func(bind orm.Scanner) error {
			return bind.Scan(&count)
		})
	})

	return count, err
}
