// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFedc9b8cDecodeGithubComOsspkgFdnsAppApi(in *jlexer.Lexer, out *AdblockRuleModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int64(in.Int64())
		case "linkId":
			out.LinkId = int64(in.Int64())
		case "rule":
			out.Rule = string(in.String())
		case "disabled":
			out.Disabled = bool(in.Bool())
		case "updatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFedc9b8cEncodeGithubComOsspkgFdnsAppApi(out *jwriter.Writer, in AdblockRuleModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	{
		const prefix string = ",\"linkId\":"
		out.RawString(prefix)
		out.Int64(int64(in.LinkId))
	}
	{
		const prefix string = ",\"rule\":"
		out.RawString(prefix)
		out.String(string(in.Rule))
	}
	{
		const prefix string = ",\"disabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Disabled))
	}
	{
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdblockRuleModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFedc9b8cEncodeGithubComOsspkgFdnsAppApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdblockRuleModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFedc9b8cEncodeGithubComOsspkgFdnsAppApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdblockRuleModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFedc9b8cDecodeGithubComOsspkgFdnsAppApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdblockRuleModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFedc9b8cDecodeGithubComOsspkgFdnsAppApi(l, v)
}
func easyjsonFedc9b8cDecodeGithubComOsspkgFdnsAppApi1(in *jlexer.Lexer, out *AdblockListModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "links":
			if in.IsNull() {
				in.Skip()
				out.Links = nil
			} else {
				in.Delim('[')
				if out.Links == nil {
					if !in.IsDelim(']') {
						out.Links = make([]AdblockLinkModel, 0, 1)
					} else {
						out.Links = []AdblockLinkModel{}
					}
				} else {
					out.Links = (out.Links)[:0]
				}
				for !in.IsDelim(']') {
					var v1 AdblockLinkModel
					(v1).UnmarshalEasyJSON(in)
					out.Links = append(out.Links, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "rules":
			if in.IsNull() {
				in.Skip()
				out.Rules = nil
			} else {
				in.Delim('[')
				if out.Rules == nil {
					if !in.IsDelim(']') {
						out.Rules = make([]AdblockRuleModel, 0, 1)
					} else {
						out.Rules = []AdblockRuleModel{}
					}
				} else {
					out.Rules = (out.Rules)[:0]
				}
				for !in.IsDelim(']') {
					var v2 AdblockRuleModel
					(v2).UnmarshalEasyJSON(in)
					out.Rules = append(out.Rules, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFedc9b8cEncodeGithubComOsspkgFdnsAppApi1(out *jwriter.Writer, in AdblockListModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"links\":"
		out.RawString(prefix[1:])
		if in.Links == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Links {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"rules\":"
		out.RawString(prefix)
		if in.Rules == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Rules {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdblockListModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFedc9b8cEncodeGithubComOsspkgFdnsAppApi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdblockListModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFedc9b8cEncodeGithubComOsspkgFdnsAppApi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdblockListModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFedc9b8cDecodeGithubComOsspkgFdnsAppApi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdblockListModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFedc9b8cDecodeGithubComOsspkgFdnsAppApi1(l, v)
}
func easyjsonFedc9b8cDecodeGithubComOsspkgFdnsAppApi2(in *jlexer.Lexer, out *AdblockLinkModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int64(in.Int64())
		case "link":
			out.Link = string(in.String())
		case "disabled":
			out.Disabled = bool(in.Bool())
		case "updatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFedc9b8cEncodeGithubComOsspkgFdnsAppApi2(out *jwriter.Writer, in AdblockLinkModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	{
		const prefix string = ",\"link\":"
		out.RawString(prefix)
		out.String(string(in.Link))
	}
	{
		const prefix string = ",\"disabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.Disabled))
	}
	{
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdblockLinkModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFedc9b8cEncodeGithubComOsspkgFdnsAppApi2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdblockLinkModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFedc9b8cEncodeGithubComOsspkgFdnsAppApi2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdblockLinkModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFedc9b8cDecodeGithubComOsspkgFdnsAppApi2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdblockLinkModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFedc9b8cDecodeGithubComOsspkgFdnsAppApi2(l, v)
}
